Fix publish.yml logic.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -56,6 +56,32 @@ jobs:
       - name: Install Python dependencies
         run: |
               python -m pip install pre-commit
+      - name: Lint, format and static analysis
+        run: |
+              /bin/bash -x ./run.sh lint:ci
+
+  # build-wheel-and-sdist:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       python-version: ["3.13"]
+  #   steps:
+  #     - name: Set up Python ${{ matrix.python-version }}
+  #       uses: actions/setup-python@v5
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #     - name: Build
+  #       run: |
+  #         ./run.sh build
+
+  #     - name: Display contents of ./dist
+  #       run: ls -l ./dist
+  #     - name: Upload wheel and sdist artifacts
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: wheel-and-sdist
+  #         path: ./dist/*
+
 
   build-wheel-and-sdist:
     runs-on: ubuntu-latest
@@ -63,21 +89,26 @@ jobs:
       matrix:
         python-version: ["3.13"]
     steps:
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}     
-      - name: Build
-        run: |
-          ./run.sh build
-
-      - name: Display contents of ./dist
-        run: ls -l ./dist  
-      - name: Upload wheel and sdist artifacts
-        uses: actions/upload-artifact@v3
-        with:
-          name: wheel-and-sdist
-          path: ./dist/*
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v5
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Build
+      run: |
+        /bin/bash -x ./run.sh build
+    - name: Ensure ./dist is not empty
+      run: |
+        if [ ! -d ./dist ] || [ -z "$(ls -A ./dist)" ]; then
+          echo "Error: ./dist directory is empty or missing. Ensure the build step creates files in ./dist."
+          exit 1
+        fi
+    - name: Display contents of ./dist
+      run: ls -l ./dist
+    - name: Upload wheel and sdist artifacts
+      uses: actions/upload-artifact@v3
+      with:
+        name: wheel-and-sdist
+        path: ./dist/*
 
   publish:
     needs:
