Remove verstion.txt job temporarily.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -15,25 +15,25 @@ env: # This is the environment variables section Global variables
 
 jobs:
 
-  check-version-txt:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check version.txt
-        run: |
-          if [ ! -f ./version.txt ]; then
-            echo "version.txt file not found!"
-            exit 1
-          fi
-          if ! grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$' version.txt; then
-            echo "version.txt does not contain a valid version number!"
-            exit 1
-          fi
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # Fetch all history for all branches and tags
-      - name: Tag with Release Version
-        run: |
-            git tag $(cat version.txt)
+  # check-version-txt:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check version.txt
+  #       run: |
+  #         if [ ! -f ./version.txt ]; then
+  #           echo "version.txt file not found!"
+  #           exit 1
+  #         fi
+  #         if ! grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$' version.txt; then
+  #           echo "version.txt does not contain a valid version number!"
+  #           exit 1
+  #         fi
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0 # Fetch all history for all branches and tags
+  #     - name: Tag with Release Version
+  #       run: |
+  #           git tag $(cat version.txt)
 
   lint-format-and-staic-analysis:
     runs-on: ubuntu-latest
@@ -86,7 +86,7 @@ jobs:
     needs:
       - build-wheel-and-sdist
       - lint-format-and-staic-analysis
-      - check-version-txt
+      # - check-version-txt
     runs-on: ubuntu-latest
     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
 
